# Generated by Django 4.2.15 on 2024-08-21 06:15

from django.db import migrations, models
import survey.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("password", models.CharField(max_length=128)),
            ],
            options={
                "db_table": "admin_user",
            },
        ),
        migrations.CreateModel(
            name="SurveyResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("position", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("question_1", models.CharField(max_length=255)),
                ("question_2", models.CharField(max_length=255)),
                ("question_3", models.CharField(max_length=255)),
                (
                    "question_4",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=survey.models.user_directory_path,
                    ),
                ),
                ("question_5", models.TextField()),
                ("question_6", models.CharField(max_length=255)),
                (
                    "question_7",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=survey.models.user_directory_path,
                    ),
                ),
                (
                    "question_8",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=survey.models.user_directory_path,
                    ),
                ),
                ("question_9", models.CharField(max_length=255)),
                ("question_10", models.CharField(max_length=255)),
                ("question_11", models.CharField(max_length=255)),
                ("question_12", models.CharField(max_length=255)),
                ("question_13", models.CharField(max_length=255)),
            ],
        ),
    ]
